# Generated by Django 4.2 on 2025-10-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTokenDtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.CharField(blank=True, max_length=50, null=True)),
                ('loginId', models.CharField(blank=True, max_length=50, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'auth_token',
            },
        ),
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailId', models.CharField(max_length=250, null=True)),
                ('otp', models.CharField(max_length=200, null=True)),
                ('key', models.CharField(max_length=200, null=True)),
                ('date_time', models.CharField(max_length=200, null=True)),
                ('createddate', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'otptbl',
            },
        ),
        migrations.CreateModel(
            name='passwordChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminId', models.CharField(max_length=250, null=True)),
                ('changeddate', models.CharField(max_length=200, null=True)),
                ('createddate', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'passwordchangehistorytbl',
            },
        ),
        migrations.CreateModel(
            name='superadmin_loginhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginId', models.CharField(max_length=250, null=True)),
                ('logineddate', models.CharField(blank=True, max_length=50, null=True)),
                ('loginedtime', models.CharField(max_length=200, null=True)),
                ('loginbrowser', models.CharField(max_length=200, null=True)),
                ('createddate', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'super_adminloginhistorytbl',
            },
        ),
        migrations.CreateModel(
            name='superadmintbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('emailId', models.CharField(max_length=250, null=True)),
                ('lastlogined', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('createddate', models.CharField(max_length=200, null=True)),
                ('loginId', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'super_admintbl',
            },
        ),
    ]
