# Generated by Django 4.2 on 2025-10-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chellotteAdmin_Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerId', models.CharField(max_length=250, null=True)),
                ('bannerurl', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(max_length=250, null=True)),
                ('createdId', models.CharField(max_length=250, null=True)),
                ('createddate', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'banner_tbl',
            },
        ),
    ]
