# Generated by Django 4.2 on 2025-10-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chellotteAdmin_Backend', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Heritage with a Purpose since 1927', max_length=255)),
                ('description', models.TextField()),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='estate/')),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='estate/')),
                ('status', models.CharField(max_length=250, null=True)),
                ('createdId', models.CharField(max_length=250, null=True)),
                ('createddate', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timelineId', models.CharField(max_length=100)),
                ('year_or_period', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
