# Generated by Django 4.2 on 2025-10-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chellotteAdmin_Backend', '0003_estateinfo_timelineevent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estateinfo',
            table='estate_tbl',
        ),
    ]
