# Generated by Django 4.2 on 2025-10-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chellotteAdmin_Backend', '0004_alter_estateinfo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estateinfo',
            table='estateinfo_tbl',
        ),
    ]
