# Generated by Django 4.2 on 2025-10-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chellotteAdmin_Backend', '0005_alter_estateinfo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={},
        ),
        migrations.AlterModelTable(
            name='timelineevent',
            table='timeline_tbl',
        ),
    ]
