# Generated by Django 4.2 on 2025-10-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chellotteAdmin_Backend', '0006_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='createdId',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='createddate',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='status',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
